# Config strings
aperture.config:
    title: Aperture
    
    general:
        title: Geral
        tooltip: Opções gerais da câmera

        duration: Duração do suporte
        spectator: Mudar para espectador
        step_factor: Fator de etapa da câmera
        rotate_factor: Fator de rotação da câmera
        command_name: Nome do comando da câmera
        debug_ticks: Depuração de ticks
        profile_render: Renderizar perfil da câmera
        auto_save: Salvar perfis automaticamente
        essentials_tp: Usar /minecraft:tp

    outside:
        title: Modo externo
        tooltip: Opções de configuração relacionadas ao modo externo
        
        enabled: Modo externo
        hide_player: Ocultar jogador
        sky: Fixar céu

    editor:
        title: Editor de câmera
        tooltip: Opções de configuração usadas no editor de câmera
        
        sync: Modo de sincronização
        loop: Loop do suporte
        overlay: Ativar sobreposição
        overlay_rl: Caminho de sobreposição
        f1_tooltip: F1 ocultar dica
        position: Exibir posição
        rule_of_thirds: Regra dos terços
        crosshair: Mira
        letter_box: Caixa postal
        aspect_ratio: Proporção da tela

    flight:
        title: Modo de voo
        tooltip: Esta categoria permite que você defina teclas de atalho para as teclas do modo de voo no editor de câmera

        forward: Mover para Frente
        backward: Mover para Trás
        left: Mover para Esquerda
        right: Mover para Direita
        up: Mover para Cima
        down: Mover para Baixo
        camera_up: Inclinar para Cima
        camera_down: Inclinar para Baixo
        camera_left: Deslocar para Esquerda
        camera_right: Deslocar para Direita
        fov_minus: Diminuir FOV
        fov_plus: Aumentar FOV
        roll_minus: Rolar para Esquerda
        roll_plus: Rolar para Direita
        speed_minus: Diminuir Velocidade
        speed_plus: Aumentar Velocidade

    smooth:
        title: Câmera suave
        tooltip: Opções de câmera suave

        enabled: Câmera suave ativada
        x_friction: Deslizamento do mouse X
        y_friction: Deslizamento do mouse Y
        clamp: Limite de inclinação
        roll_speed: Velocidade de rolagem
        roll_friction: Deslizamento de rolagem
        fov_speed: Velocidade do FOV
        fov_friction: Deslizamento do FOV
