# Config strings
aperture.config.comments:
    camera:
        camera_duration_step: Etapa padrão a ser usada ao adicionar ou reduzir a duração do equipamento da câmera (em ticks)
        camera_duration: Duração padrão do equipamento da câmera (em ticks)
        camera_interpolate_target: Alterne o resultado dos acessórios de câmera com base em alvo (siga e observe)
        camera_interpolate_target_value: Valor da interpolação para interpolação de acessórios de câmera com base em alvo
        camera_spectator: Alterne para o modo de espectador ao iniciar a reprodução da câmera
        camera_step_factor: Fator de etapa da câmera para teclas de etapas
        camera_rotate_factor: Fator de rotação da câmera para girar as teclas
        camera_minema: Ative a gravação do Minema na inicialização da câmera e desative na parada da câmera
        camera_path_default_interp: Método de interpolação padrão para fixação de caminho
        camera_command_name: Permite religar o nome do comando da câmera (requer que o jogo seja reiniciado)
        camera_simulate_velocity: Simule a velocidade do player durante a reprodução da câmera (veja as pernas em perspectiva)
        camera_debug_ticks: Escreva o tick atual da reprodução da câmera no log
        camera_first_tick_zero: Quando o corredor da câmera iniciar, inicie a reprodução real quando o tick parcial for exatamente zero
        camera_profile_render: Renderizar perfil de câmera no mundo?
        camera_auto_save: Salve todos os perfis de câmera ao sair do mundo
        gui_render_mouse: Renderizar na tela a textura de um ponteiro do mouse durante a GUI
        minecrafttp_teleport: Ao iniciar a reprodução da câmera no modo multiplayer, teleporte-o com o comando /minecraft:tp (para o Essentials)
        tp_teleport: Ao iniciar a reprodução da câmera no modo multiplayer, teleporte-o com o comando /tp (para Vanilla ou Forge)
        aspect_ratio: Relação de aspecto para o recurso de caixa de correio do editor de câmera
        
    outside:
        camera_outside: Se a câmera deve ser reproduzida de fora (permitindo que o jogador atue como um ator)
        camera_outside_hide_player: Se o player deve ficar oculto durante a reprodução da câmera, se o modo externo estiver ativado
        camera_outside_sky: Se ativado, corrige o céu, mas desativa a seleção de blocos (devido a um bug)
        camera_outside_hide_guis: Impedir que as telas da GUI sejam renderizadas durante o modo externo
        camera_outside_hide_overlays: Impedir sobreposições da tela de renderização (como sobreposição de abóbora, fogo ao queimar, água e etc.) durante o modo externo

    overlay:
        camera_editor_overlay: Ativa a sobreposição do editor de câmera
        camera_editor_overlay_rl: Caminho do local do recurso para a textura que será usada como sobreposição

    smooth:
        camera_smooth_clamp: Prender da afinação suave da câmera entre -90 e 90 graus?

        roll_speed: Velocidade de aceleração do rolamento
        roll_friction: Atrito de aceleração do rolamento (com que rapidez diminui)

        fov_speed: Velocidade de aceleração FOV
        fov_friction: Atrito de aceleração FOV (com que rapidez diminui)

        smooth_enabled: Ativar câmera suave.
        mouse_x_friction: Atrito suave do mouse X
        mouse_y_friction: Atrito suave do mouse Y
