# Config strings
aperture.config.comments:
    general:
        duration: What is default duration of the camera fixture (in ticks)
        spectator: Switch to spectator mode when starting camera playback
        step_factor: Camera step factor for step keys
        rotate_factor: Camera rotate factor for rotate keys
        command_name: Allows you to rebind camera command's name (requires game reload to take effect)
        debug_ticks: Write current camera playback tick to the log
        profile_render: Render camera profile in the world?
        auto_save: Save all camera profiles upon exiting the world
        essentials_tp: When start the camera playback in multiplayer, teleport you with /minecraft:tp command (For Essentials)

    outside:
       enabled: Whether camera should be played back from outside (allowing the player to act as a body actor)
       hide_player: Whether player should be hidden during playback of the camera if outside mode is enabled
       sky: If enabled, fixes the sky, but disables block selection (due to a bug)

    editor:
        sync: Enables syncing of camera's position in camera editor, which previews current camera profile
        loop: Loops playback of currently selected fixture
        overlay: Enables camera editor overlay
        overlay_rl: Resource location path to the texture which will be used as overlay
        f1_tooltip: Show the tooltip in the bottom left corner which explains how to show back the GUI
        position: Show camera properties when sync mode enabled
        rule_of_thirds: Show rule of thirds guides
        crosshair: Show a crosshair in the middle of the camera editor's screen
        letter_box: Show letter box (aka black bars) which narrow or widen the camera shot as a reference
        aspect_ratio: Aspect ratio for camera editor's letterbox feature

    flight:
        forward: Moves the camera forward
        backward: Moves the camera backward
        left: Moves the camera to the left
        right: Moves the camera to the right
        up: Ascends the camera upward
        down: Descends the camera downwards
        camera_up: Tilt the camera upward toward the sky
        camera_down: Tilt the camera downward toward the ground
        camera_left: Pan the camera to the left
        camera_right: Pan the camera to the right
        fov_minus: Narrow the Field of View
        fov_plus: Widen the Field of View
        roll_minus: Roll counter-clockwise
        roll_plus: Roll clockwise
        speed_minus: Decrease overall speed factor (instead of mouse wheel down)
        speed_plus: Increase overall speed factor (instead of mouse wheel up)

    smooth:
        enabled: Enable smooth camera
        x_friction: Smooth mouse X friction
        y_friction: Smooth mouse Y friction
        clamp: Clip smooth camera's pitch between -90 and 90 degrees range?
        roll_speed: Roll acceleration speed
        roll_friction: Roll acceleration friction (how fast it slows down)
        fov_speed: FOV acceleration speed
        fov_friction: FOV acceleration friction (how fast it slows down)