# Config strings
aperture.config:
    title: Aperture

    general:
        title: General
        tooltip: General camera options

        duration: Fixture duration
        spectator: Switch to specator
        step_factor: Camera step factor
        rotate_factor: Camera rotate factor
        command_name: Camera command name
        debug_ticks: Debug ticks
        profile_render: Render camera profile
        auto_save: Auto save profiles
        essentials_tp: Use /minecraft:tp

    outside:
        title: Outside mode
        tooltip: Config options related to outside mode
        
        enabled: Outside mode
        hide_player: Hide player
        sky: Fix sky

    editor:
        title: Camera editor
        tooltip: Config options which are used within camera editor

        sync: Sync mode
        loop: Loop fixture
        overlay: Enable overlay
        overlay_rl: Overlay path
        f1_tooltip: F1 hide tooltip
        position: Display position
        rule_of_thirds: Rule of thirds
        crosshair: Crosshair
        letter_box: Letter box
        aspect_ratio: Aspect ratio

    flight:
        title: Flight mode
        tooltip: This category allows you to set keybinds for flight mode keys within camera editor

        forward: Move forward
        backward: Move backward
        left: Move left
        right: Move right
        up: Move upward
        down: Move downward
        camera_up: Tilt up
        camera_down: Tilt down
        camera_left: Pan left
        camera_right: Pan right
        fov_minus: Decrease FOV
        fov_plus: Increase FOV
        roll_minus: Roll left
        roll_plus: Roll right

    smooth:
        title: Smooth camera
        tooltip: Smooth camera options

        enabled: Smooth camera enabled
        x_friction: Mouse X friction
        y_friction: Mouse Y friction
        clamp: Limit pitch
        roll_speed: Roll speed
        roll_friction: Roll friction
        fov_speed: FOV speed
        fov_friction: FOV friction