# Config strings
aperture.config:
    title: Aperture

    general:
        title: 常规
        tooltip: 常规相机选项

        duration: 关键点持续时间
        spectator: 切换至旁观者模式
        step_factor: 相机位移系数
        rotate_factor: 相机旋转系数
        command_name: 相机命令名称
        debug_ticks: 调试 Ticks
        profile_render: 渲染相机配置
        auto_save: 自动保存配置
        essentials_tp: 使用 /minecraft:tp

    outside:
        title: 分离像机模式
        tooltip: 与分离相机模式相关的选项

        enabled: 分离相机模式
        hide_player: 隐藏玩家
        sky: 修复天空

    editor:
        title: 相机编辑器
        tooltip: 应用于相机编辑器的选项

        sync: 同步模式
        loop: 循环播放
        overlay: 启用附加层
        overlay_rl: 附加层路径
        f1_tooltip: 隐藏 F1 提示
        position: 显示位置信息
        guides_color: 辅助线颜色
        rule_of_thirds: 三分法构图辅助线
        center_lines: 中心构图辅助线
        crosshair: 十字准心
        letter_box: 画面黑边
        aspect_ratio: 纵横比
        hide_chat: 隐藏聊天栏
        seconds: 以秒为单位
        auto_save: 自动保存周期

    flight:
        title: 飞行模式
        tooltip: 该分类允许您为相机编辑器中的飞行模式设置快捷键

        forward: 向前移动
        backward: 向后移动
        left: 向左移动
        right: 向右移动
        up: 向上移动
        down: 向下移动
        camera_up: 上摇
        camera_down: 下摇
        camera_left: 左摇
        camera_right: 右摇
        fov_minus: 缩小 FOV
        fov_plus: 增大 FOV
        roll_minus: 向左翻滚
        roll_plus: 向右翻滚
        speed_minus: 降低速度
        speed_plus: 提升速度

    smooth:
        title: 平滑相机
        tooltip: 平滑相机选项

        enabled: 启用平滑相机
        x_friction: 鼠标 X 轴摩擦力
        y_friction: 鼠标 Y 轴摩擦力
        clamp: 限制俯仰
        roll_speed: 倾斜速度
        roll_friction: 倾斜摩擦力
        fov_speed: FOV 速度
        fov_friction: FOV 摩擦力

    minema:
        title: Minema
        tooltip: 与 Minema 相关的集成工作选项

        default_profile_name: 相机配置名称

    optifine:
        title: Optifine
        tooltip: 与 Optifine 相关选项

        shader_option_curve: 光影包选项曲线

op_access.config.aperture:
    title: Aperture
    tooltip: Aperture OP 访问权限选项

    camera_editor: 相机编辑器
