# Config strings
aperture.config:
    title: Аперчер

    general:
        title: Общие
        tooltip: Общие настройки камеры

        duration: Продолжительность клипов
        spectator: Переключение на наблюдателя
        step_factor: Фактор шага камеры
        rotate_factor: Фактор вращения камеры
        command_name: Название команды камеры
        debug_ticks: Тики отладки
        profile_render: Отображать профиль камеры
        auto_save: Автосохранение профилей
        essentials_tp: Использовать /minecraft:tp

    outside: 
        title: Внешний режим
        tooltip: Настройки связанные с внешним режимом

        enabled: Внешний режим
        hide_player: Спрятать игрок
        sky: Починить небо

    editor:
        title: Редактор камеры
        tooltip: Настройки конфигурации, используемые в редакторе камеры

        sync: Режим синхронизации
        loop: Закольцевать клип
        overlay: Включить оверлэй
        overlay_rl: Путь оверлэя
        f1_tooltip: Спрятать подсказку на F1
        position: Отображать позицию
        guides_color: Цвет направляющих
        rule_of_thirds: Правило третей
        center_lines: Центр экрана
        crosshair: Перекрестие
        letter_box: Каше
        aspect_ratio: Соотношение сторон
        hide_chat: Спрятать чат
        seconds: Использовать секунды
        auto_save: Периодическое автосохранение

    flight:
        title: Режим полёта
        tooltip: Эта категория позволяет вам назначать клавиши для кнопок режима полёта в редакторе камеры

        forward: Двигаться вперёд
        backward: Двигаться назад
        left: Двигаться влево
        right: Двигаться вправо
        up: Двигаться вверх
        down: Двигаться вниз
        camera_up: Повернуться наверх
        camera_down: Повернуться вниз
        camera_left: Повернуться влево
        camera_right: Повернуться вправо
        fov_minus: Уменьшить поле зрения
        fov_plus: Увеличить поле зрения
        roll_minus: Кренить влево
        roll_plus: Кренить вправо
        speed_minus: Уменьшить скорость
        speed_plus: Увеличить скорость

    smooth:
        title: Гладкое движение камеры
        tooltip: Настройки гладкого движения камеры

        enabled: Гладкое движение камеры включено
        x_friction: Ослабление оси X
        y_friction: Ослабление оси Y
        clamp: Ограничить тангаж
        roll_speed: Скорость крена
        roll_friction: Ослабление крена
        fov_speed: Скорость поля зрения
        fov_friction: Ослабление поля зрения

    minema:
        title: Минема
        tooltip: Опции, касающиеся интеграции минемы

        default_profile_name: Название профиля камеры

op_access.config.aperture:
    title: Aperture
    tooltip: Настройки ОП-доступа Aperture

    camera_editor: Редактор камеры
