# Config strings
aperture.config.comments:
    general:
        duration: Значение продолжительности клипа по умолчанию (в тиках)
        spectator: Переключение в режим наблюдателя во время начала воспроизведения камеры
        step_factor: Фактор шага камеры для кнопок шага
        rotate_factor: Фактор вращения камеры для кнопок вращения
        command_name: Позволяет вам переназначить команду камеры (для применения необходим перезапуск игры)
        debug_ticks: Записывает тики текущего воспроизведения камеры в лог
        profile_render: Отображать профиль камеры в мире?
        auto_save: Сохранять все профили во время выхода из мира
        essentials_tp: Необходимо ли телепортировать вас командой /minecraft:tp (для Essentials), когда начинется воспроизведение камеры в мультиплеере

    outside:
       enabled: Должна ли быть камера воспроизведена снаружи (позволяя игроку быть актером)
       hide_player: Должен ли быть игрок спрятан во время воспроизведения записи если включен внешний режим?
       sky: Если включено, то исправляет небо, но отключает выбор блока (из-за бага)
    
    editor:
        sync: Включает синхронизацию позиции камеры в редакторе камеры, что делает возможным предпросмотр текущего профиля камеры
        loop: Закольцовывает воспроизведение выбранного клипа
        overlay: Включает оверлей редактора камеры
        overlay_rl: Путь к текстуре, которая будет использована в качестве оверлэя
        f1_tooltip: Показывать подсказку в левом нижнем углу которая объясняет как включить интерфейс обратно
        position: Показывать свойства камеры при включённом режиме синхронизации
        guides_color: Выбрать цвет рамок правила третей или центра экрана (поддерживает прозрачность)
        rule_of_thirds: Показывать рамку правила третей
        center_lines: Показывать рамку центра экрана
        crosshair: Показывать перекрестие посреди экрана редактора камеры
        letter_box: Показывать каше (aka чёрные полосы), которые сужают видимое пространство, захватываемое камерой
        aspect_ratio: Пропорции для каше редактора камеры
        hide_chat: При включении, эта опция прячет чат, которое может довольно сильно отвлекать при расстановке кадров и ракурсов

    flight:
        forward: Передвинуть камеру вперёд
        backward: Передвинуть камеру назад
        left: Передвинуть камеру влево
        right: Передвинуть камеру вправо
        up: Поднять камеру вверх
        down: Опустить камеру вниз
        camera_up: Напрвить камеру наверх, к небу
        camera_down: Направить камеру вниз, к земле
        camera_left: Повернуть камеру налево
        camera_right: Повернуть камеру направо
        fov_minus: Сузить поле зрения
        fov_plus: Расширить поле зрения
        roll_minus: Кренить против часовой стрелки
        roll_plus: Кренить по часовой стрелке
        speed_minus: Уменьшить общий фактор скорости (вместо прокрутки колёсиком мыши вниз)
        speed_plus: Увеличить общий фактор скорости (вместо прокрутки колёсиком мыши вверх)

    smooth:
        enabled: Включить гладкое движение камеры.
        x_friction: Ослабление гладкости по оси Х
        y_friction: Ослабление гладкости по оси Y
        clamp: Ограничить тангаж камеры до -90 и 90 градусов?
        roll_speed: Скорость ускорения крена
        roll_friction: Ослабление скорости крена (насколько быстро он замедляется)
        fov_speed: Скорость ускорения поля зрения
        fov_friction: Ослабление скорости поля зрения (насколько быстро оно замедляется)

    minema:
        default_profile_name: Должно ли быть выходное имя файла названием профиля, а не текущей датой
